### ISSUE TITLE
"Shift" section for Arithmetic  R Instructions

### ISSUE THREAD

**Issue by fyquah** [m8pple/arch2-2015-cw1#10]
According to docs, SUBU (amongst others like ADD, SUB that isn't shift) has a `shift` value of 0. if `shift != 0` should it be an invalid instruction?

**Comment by m8pple** [comment]
Yes, that would be an invalid instruction. ISAs are intended to be very restricted, so
things that are not explicitly allowed are implicitly disallowed - it's a "deny all, then
allow some" policy.

It's a bit different to things like HTML, networking, and file formats, where [Postel's Principle](https://en.wikipedia.org/wiki/Robustness_principle) applies. Though even there it
is going out of fashion a bit.
