### ISSUE TITLE
Possible ambiguity with execution of load byte instruction

### ISSUE THREAD

**Issue by adityarajagopal** [m8pple/arch2-2015-cw1#12]
The load byte instruction would not need a memory address that is a multiple of 4 as accessing bytes within the word should be possible. However as the block size has been specified as 4 for the simulated processor, and also memory access to any unaligned address throws an InvalidAllignment error, accessing a single byte within the word is not possible in our cpu. 

Possible workarounds: 
1) Only allow aligned memory reads, thus allowing access to only the least significant byte of a memory word. 
2) Within our cpu code, identify the word within which the required byte is in and pass an aligned address for the memory read. On receiving the word, isolate the required byte. 

Option 1 seems to be the more valid option as the restriction of a minimum data transfer of 4 bytes would by default place a restriction on single byte operations and also option 2 does not seem as a calculation that would happen within the cpu.

**Comment by m8pple** [comment]
I would observe that:
- LB exists as a MIPS instruction. It allows reading of bytes at arbitrary
  non-aligned addresses within RAM, and works in actual hardware.
- MIPS is a 32-bit ISA, and the data-path between the CPU and the memory
  is 32-bits. For example, see the entity `mlite_cpu` at [this page](http://opencores.com/project,plasma).
  You can see all the signals, and the `data_r` and `data_w` are both 32-bit.

So if memory reads and writes must be 32-bits and aligned at the CPU-to-memory
interface, and unaligned addresses can be read using the LB instruction,
that means that option 2 must be in effect - the byte extraction is happening _within_
the CPU, while the address given to memory is the word-aligned address
containing the requested byte.

If you think of the hardware cost for this, you need a multiplexor which is able
to move one of the four bytes read from memory into the least-significant byte of
the word that will be written to the register file. Not a lot of hardware, and it
can be indexed by the two LSBs of the byte address.

If that doesn't make sense, feel free to re-open the issue.

(You might wonder about how a real CPU would handle SB, as option 2
would require a read-update-write approach to change one byte in memory. That
would take 3 cycles, which is against the RISC principles of MIPS. However,
notice another signal called `byte_we` on the [`mlite_cpu` interface](http://opencores.com/project,plasma). That signal is four-bits wide, and is used
to control whether each of the four bytes is written within a given 32-bit
write. Its a bit beyond the immediate scope of this course though.)
