### ISSUE TITLE
Naming subfolders

### ISSUE THREAD

**Issue by nikonikolov** [m8pple/arch2-2015-cw1#13]
Do we need to follow the name requirements for names of subfolders as well? In the current version of the makefile all subfolders will get compiled. However, that can cause some issues if tests are swapped around between different submissions. E.g. right now my test suite needs SOME of the subfolders to run, but not ALL of them. There is no clear way to distinguish the subfolders you need only from their names, though, without reading the code and tracking all headers back. Possible solution might be to name all test related files/subfolders test_mips_\* and all cpu-related ones mips_cpu_*.

**Comment by m8pple** [comment]
I'm pretty open on this, so as long as it is a clear specification
that can be expressed in glob patterns unambiguously, then
I don't mind.

I think you and @fyquah95 are the main clients of this functionality. Could you
give a tighter specification of your solution (in text and ideally explicit file patterns)?

**Comment by fyquah** [comment]
It doesn't seem to be really clear (at least according to the current makefile) on the distinction between test suite and CPU sites.

Something like this'd be much clearer:

``` bash
USER_CPU_SRC =\
  $(wildcard src/$(LOGIN)/mips_cpu.c) \
  $(wildcard src/$(LOGIN)/mips_cpu.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.cpp) \
  $(wildcard src/$(LOGIN)/*/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/*/mips_cpu_*.cpp) \
TEST_SRC=\
  $(wildcard src/$(LOGIN)/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/test_mips_*.cpp)
  $(wildcard src/$(LOGIN)/*/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/*/test_mips_*.cpp)
```

With this Makefile, we (can?) safely assume that something that matches `mips_cpu_*.c(pp)*` will be compiled as part of the CPU and `test_mips_*.c(pp)` will be compiled as part of the test suite, as long as they are in `src/$(LOGIN)` or `src/$(LOGIN)/*`

**Comment by nikonikolov** [comment]
I agree with @fyquah95 . Probably it would be clearer though if it's structured like this:

<pre><code>USER_CPU_SRC =\
  $(wildcard src/$(LOGIN)/mips_cpu.c) \
  $(wildcard src/$(LOGIN)/mips_cpu.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu_*/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/mips_cpu_*/mips_cpu_*.cpp) \
TEST_SRC=\
  $(wildcard src/$(LOGIN)/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/test_mips_*.cpp) \
  $(wildcard src/$(LOGIN)/test_mips_*/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/test_mips_*/test_mips_*.cpp)
</code></pre>

I hope that would not make everybody run into huge problems with changing names in their projects

**Comment by nikonikolov** [comment]
Also, currently the makefile does not compile any files named `test_mips_*.cpp` or `test_mips_*.c`

**Comment by m8pple** [comment]
That's an excellent point - I just looked at my assessment build rules, and I have a different
pattern that does bring things in according to the spec, but yes, that is broken.

I'm reluctant to commit to master right now (as I can't test where I am). If you look
on the staging branch, does this https://github.com/m8pple/arch2-2015-cw1/commit/ab3e5732ab8d20ccb57cad5738cb5899e2e2d6c8 look ok?

**Comment by nikonikolov** [comment]
Looks good to me. Probably a `make clean` functionality will also be good addition.

**Comment by nikonikolov** [comment]
Actually, is it possible to have a structure like this:

<pre><code>USER_CPU_SRC =\
  $(wildcard src/$(LOGIN)/mips_cpu.c) \
  $(wildcard src/$(LOGIN)/mips_cpu.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/mips_cpu_*.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu_*/mips_cpu_*.c) \
  $(wildcard src/$(LOGIN)/mips_cpu_*/mips_cpu_*.cpp)
COMMON_SRC=\
  $(wildcard src/$(LOGIN)/common_*.c) \
  $(wildcard src/$(LOGIN)/common_*.cpp) \
  $(wildcard src/$(LOGIN)/common_*/common_*.c) \
  $(wildcard src/$(LOGIN)/common_*/common_*.cpp)
TEST_SRC=\
  $(wildcard src/$(LOGIN)/test_mips.c) \
  $(wildcard src/$(LOGIN)/test_mips.cpp) \  
  $(wildcard src/$(LOGIN)/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/test_mips_*.cpp) \
  $(wildcard src/$(LOGIN)/test_mips_*/test_mips_*.c) \
  $(wildcard src/$(LOGIN)/test_mips_*/test_mips_*.cpp) </code></pre>

The reason for adding `COMMON_SRC` is to allow for definition of some functions that are used both by the cpu and the test, e.g. changing endianness, printing Debug messages, etc. When tests are swapped around between different submissions, each simulator can keep it's `common_*.c/cpp` files and each `TEST_SRC` can be copied together with it's  `common_*.c/cpp`. Thus each program will end up with `common_*.c/cpp` files both from the original cpu and the newly introduced `TEST_SRC`. I cannot think of a way somebody will be able to cheat, since even if there are some functions defined in  `COMMON_SRC` which break the encapsulation of the cpu and the test framework, when tests are swapped, the simulator will disastrously fail.

P.S. I also think that in the link for the staging branch you gave us, there should NOT be a slash at the end of line 24.

**Comment by nikonikolov** [comment]
Just realized sht else. Printing is especially difficult to do both in the test framework and in the cpu. The reason is that there is no official API for getting the logLevel and logDestination. The motivation for those is that printing proves to be really useful in the test suite as well. E.g. I am reading my tests from a file and want to check whether I have read the file correctly.

**Comment by m8pple** [comment]
Final version:

USER_CPU_SRC =\
  $(wildcard src/$(LOGIN)/mips_cpu.c) \
  $(wildcard src/$(LOGIN)/mips_cpu.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu__.c) \
  $(wildcard src/$(LOGIN)/mips_cpu__.cpp) \
  $(wildcard src/$(LOGIN)/mips_cpu__/mips_cpu__.c) \
  $(wildcard src/$(LOGIN)/mips_cpu__/mips_cpu__.cpp) \

TEST_SRC=\
  $(wildcard src/$(LOGIN)/test_mips__.c) \
  $(wildcard src/$(LOGIN)/test_mips__.cpp) \
  $(wildcard src/$(LOGIN)/test_mips__/test_mips__.c) \
  $(wildcard src/$(LOGIN)/test_mips__/test_mips__.cpp)
