### ISSUE TITLE
Invalid Alignment vs Address Error Exception

### ISSUE THREAD

**Issue by jeg114** [m8pple/arch2-2015-cw1#14]
When reading from memory if the address is not correctly aligned `mips_mem_ram` returns an  `mips_ExceptionInvalidAlignment` however according to several the  <a href="http://math-atlas.sourceforge.net/devel/assembly/mips-iv.pdf">
specifications</a> instructions such as `JR` : 

`"The effective target address in GPR rs must be naturally aligned. If either of the two
least-significant bits are not -zero, then an Address Error exception occurs, not for the
jump instruction, but when the branch target is subsequently fetched as an instruction."`

I can´t find any mention to `mips_ExceptionInvalidAlignment` so my issue is should we return an `mips_ExceptionInvalidAlignment` when we are expected to return an Address Error exception, or should `mips_ExceptionInvalidAlignment` be changed to `mips_ExceptionAddressError`

**Comment by m8pple** [comment]
I would say that either `mips_ExceptionInvalidAddress` or `mips_ExceptionInvalidAlignment` would be appropriate in the JR case.

If a memory error occurs, an entirely reasonable response is to simply
return that as the result of `mips_cpu_step`, but I could also see the
logic in changing it to something more specific like `mips_ExceptionAddressError`.

What you're exploring here is a bit of a mis-match between the simulator
interface and the ISA specification - some things don't map one-to-one.
So while it wouldn't make sense to return an arithmetic overflow exception,
from the point of the simulator either simulator exception makes sense.

Personally, as soon as I do a memory transaction that I expect to succeed
and it doesn't, I would just return back the error from the RAM.

(Good question).
