### ISSUE TITLE
Blackboard not allowing multiple submissions

### ISSUE THREAD

**Issue by ppp2211** [m8pple/arch2-2015-cw1#15]
Blackboard doesn't seem to let anyone start a new submission after having submitted something before, despite the description stating "unlimited uploads available". Not sure if it's a glitch with Blackboard, or human error.

**Comment by Manicben** [comment]
Also, sending by email apparently doesn't work due to a "full mailbox" on the recipient's side.
For reference, here's my updated project on GitHub that I was unable to send via email.
https://github.com/Manicben/arch2-2015-cw1-bbw14

**Comment by m8pple** [comment]
Errors are human, blackboard is divine.
