### ISSUE TITLE
Undefined behaviour of MFHI, MFLO, MTHI, MTLO

### ISSUE THREAD

**Issue by jeg114** [m8pple/arch2-2015-cw1#16]
`MFHI` and `MFLO` give undefined behavior when the following two instructions contain an instruction that modifies `HI` or `LO`  and `MTHI` and `MTLO` give undefined results when a previously modified `HI` or `LO` has not yet been read by a `MFHI` and `MFLO`, if I understood correctly the specifications.

However I assume that this undefined behavior is caused by the hardware implementation of these instructions. Since our simulator is free from these restrictions it can implement these instructions without undefined behavior. Should we make them have undefined behavior, by setting the output to be a random number for example? 

Making them have undefined behavior would mean having a more precise simulator because programs that would crash on the MIPS due to this undefined behavior would also do under the simulator. However the correct output can also be considered to be undefined behavior.

**Comment by m8pple** [comment]
(Sorry for the lack of response on this).

It's an interesting question, and it comes down to who the simulator
is for. If the goal is to find a broken compiler, then your suggestion
to randomised and cause a crash makes sense.

However, if you turn it around, and think about what it is possible for me
to test, you can reason that there is no way for me to actually enforce
a particular behaviour. Whatever you do in that case would be correct,
_except_ for crashing the simulator (that would be equivalent to the
CPU catching fire).

So I would be inclined to say, just be correct by default - it is easiest.
