### ISSUE TITLE
Branch Exceptions 

### ISSUE THREAD

**Issue by nikonikolov** [m8pple/arch2-2015-cw1#17]
All questions are related to memory addresses, so I thought only one issue would be most appropriate. I could not find these mentioned in the specifications
1. Should I indicate somehow when PC overflows and returns to 0
2. When I execute a branch with negative immediate argument and the resulting number for the address is negative, do I generate an exception? What if the immediate is positive and the resulting address makes PC overflow? If yes, what is the expected exception: mips_ExceptionInvalidAddress or mips_ExceptionAccessViolation?
   3.If in fact exception is generated: say my branch instruction is at address 0x04. Do I signal the exception after the branch instruction itself, or after I execute the instruction at address 0x08

**Comment by m8pple** [comment]
Another delayed response. My reading of the specification is that it is allowed for the program
counter to overflow. I can't find any specific language that says that it can't happen. Similarly,
I think that if the PC goes negative, it just wraps round to a large value.

I don't have any specific evidence for this, but it is based on the observation that:
- The program counter is required to be 32-bit (I believe, as it must be possible to
  come in and out of a GPR, and the virtual memory system assumes 32-bit)
- It could be useful to get from a high to low address with a 16-bit offset (for OS purposes)
