### ISSUE TITLE
2's Complement Modulo

### ISSUE THREAD

**Issue by jeg114** [m8pple/arch2-2015-cw1#18]
When calculating the remainder of the `DIV` instruction the specs say it should be
 `r ← GPR[rs]31..0 mod GPR[rt]31..0` where  `mod`is defined earlier in the specs as  `2’s complement modulo.`

From this I understand that it should have a sign though there are several ways of deciding the sign, should it be according to this formula `(a/b)*b + b*(a mod b) = a`?

**Comment by adityarajagopal** [comment]
<img width="1440" alt="screen shot 2015-10-29 at 7 14 23 pm" src="https://cloud.githubusercontent.com/assets/15138792/10829358/5c28804c-7e71-11e5-9635-f41d9f0652b9.png">

Following the formula mentioned, -9 % -2, should give 1. However, according to the mips simulator shown in the snap shot, the HI register reads 0xffffffff, which is -1.

**Comment by m8pple** [comment]
A good question that I missed in the run-up to submission last year.
IMHO the MIPS ISA spec doesn't do a good job of saying what happens,
and this is handled inconsistently between languages.

I think the simplest way of dealing with it is exactly what Aditya suggested - run
it in a simulator and see what happens. A negative modulo matches what I
would expect. Even better would be to run it on a real MIPS, though arguably
this is how quirks of implementation become relied upon behaviour.

In SPIM (another simulator), they just fall back on the C modulo operator:
https://sourceforge.net/p/spimsimulator/code/HEAD/tree/CPU/run.c#l488
(That's what I did in my reference code too)
