### ISSUE TITLE
Handling invalid instructions

### ISSUE THREAD

**Issue by balassaloci** [m8pple/arch2-2015-cw1#19]
What should happen, when a half existing instruction is given to the CPU? Such as an ADD instruction, with non-zero shift bits. Is it OK that the CPU returns `mips_ErrorNotImplemented=0x1000,` or should it return `mips_ExceptionInvalidInstruction=0x2004,`

**Comment by m8pple** [comment]
To be fully correct, it should return `mips_ExceptionInvalidInstruction` - in the MIPS1 ISA
this doesn't exist, so the CPU has no way of knowing how to handle it. For later revisions
of the ISA it may become meaningful.
