### ISSUE TITLE
USER_CPU_SRC nested directories

### ISSUE THREAD

**Issue by fyquah** [m8pple/arch2-2015-cw1#2]
I figure it is appropriate to permit source files (not just header files) in nested directories at `src/<USER-NAME>`. The Makefile currently doesn't seem to compile source files in nested directories.

One obvious (I think) reason to support such structure is to allow test files and source files to be in different directories. Eg, I think it is much more appropriate to have `src/eie2ugs/main` and `src/eie2ugs/test/` instead of having everything in `src/eie2ugs`.

Edit: I made a commit that implements the above at my fork (https://github.com/fyquah95/arch2-2015-cw1/commit/2fc9ad5be773fefde3fd580e4d424be18eb3d8bb)

**Comment by m8pple** [comment]
Sure, that seems entirely reasonable.

Before updating the default makefile + readme - do you know whether the double-asterisk is
portable? It's not a pattern I generally use/see in makefiles, and I can't find it mentioned
in the manual. I know its in some shells, but I'm not sure if make is using the shell to do
the globbing or if it is doing it internally.

**Comment by fyquah** [comment]
I have used it often and never really had any problems, but I can't find it from the manual either.

Something like `$(shell find src/$(LOGIN) -name "*test_mips*.cpp")` works, but interacts with the shell. However, `find` ships with BSD , so i wouldn't really worry about it.

**Comment by m8pple** [comment]
I'm going to play it safe, and just say that I'll compile in anything in `src/<USER-NAME>` and `src/<USER_NAME>/*`. I'm reluctant to put anything I don't trust to be reasonably portable
in the main makefile, and don't really want to $(shell ...) out, as I won't have time to test it.
