### ISSUE TITLE
submission dates incorrect

### ISSUE THREAD

**Issue by lorenzo2897** [m8pple/arch2-2015-cw1#20]
In the main readme, under https://github.com/m8pple/arch2-2016-cw#assessment-criteria the dates for the formative ungraded assessment read 21st of October, both for submission and feedback. Is it meant to be Monday 24th?

**Comment by m8pple** [comment]
Yes, you're right. There is an automated component, which is very rapid,
but I then do a manual pass as well which is the part that takes a bit of time.
