### ISSUE TITLE
Txt files, how to include them?

### ISSUE THREAD

**Issue by martinferianc** [m8pple/arch2-2015-cw1#23]
Is there a way how can we use txt files for storing and loading? The file can't be opened without plugging in the entire file path. Thank you!

**Comment by m8pple** [comment]
Can you elaborate a bit more - do you mean that you want to open text files from
within your CPU, or your test code? So does that mean you want to open files
with a relative directory to your CPU?

There is a bit of legalese in the specification that addresses this:

> When running your test suite, the executable will be launched with its working
> directory as `src/[your_login]`, so if you wish to read files you can place them there
> (or in sub-directories).

So for example, if you had a file called `src/[your_login]/input.txt`, you should be
able to open it using (haven't tried compiling this):

```
std::ifstream input("input.txt", "r");
```

When testing, you could replicate the evironment by doing:

```
(cd src/[your_login] && ./test_mips)
```

This first changes directory to your private directory, then runs the executable.

Does that help?

**Comment by martinferianc** [comment]
Thank you very much, I didn't specify the directory and I run the program by a right click: open in Terminal. My fault, I should have tried that myself. Thank you!

**Comment by m8pple** [comment]
No problem, things like working directories are sometimes a bit confusing when switching
between gui and command line.
