### ISSUE TITLE
How do we run fragments/ programs?

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#24]
I was trying to run fragments/run_fibonacci as in the comments in the makefile.

After running:`make fragments/run_fibonacci`, the output of `ls fragments` contains:

```
f_addu.c         f_addu-mips.diss  f_fibonacci-mips.bin   run_addu.cpp
f_addu-mips.bin  f_fibonacci.c     f_fibonacci-mips.diss  run_fibonacci.cpp

```

There is no run_fibonacci binary/.exe/.o

I added `$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $^ $(LFLAGS) $(LDLIBS)` below `fragments/run_fibonacci : $(DEFAULT_OBJECTS) $(USER_CPU_OBJECTS)`
But then got this error:

```
g++ -W -Wall -g -I include -std=c++11 -o fragments/run_fibonacci src/shared/mips_test_framework.o src/shared/mips_mem_ram.o src/gsp14/mips_cpu.o src/gsp14/mips_cpu_extra.o  
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function '_start':
(.text+0x20): undefined reference to 'main'
collect2: error: ld returned 1 exit status
makefile:81: recipe for target 'fragments/run_fibonacci' failed
make: *** [fragments/run_fibonacci] Error 1
```

**Comment by m8pple** [comment]
Sorry, I missed this one. I was relying on a slightly obscure feature of make. Your
explicit version makes more sense, but I think what is missing is the inclusion of
`fragments /run_fibonacci.cpp` itself.

So the following rule:

```
fragments/run_fibonacci : fragments/run_fibonacci.cpp $(DEFAULT_OBJECTS) $(USER_CPU_OBJECTS)
    $(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $^ $(LFLAGS) $(LDLIBS)
```

should work (though I haven't tested it, as I don't have CPU impl where I am right now).

**Comment by ps-george** [comment]
That works,

I copy/pasted your code and needed to replace spaces in front of $(CXX) with a hard tab, then the output has to be run from inside the fragments folder.
