### ISSUE TITLE
Delay slot queries

### ISSUE THREAD

**Issue by Carotti** [m8pple/arch2-2015-cw1#29]
According to the MIPS specification, the instruction after a jump instruction (the delay slot) is executed before the jump is taken. I can appreciate why this is from a hardware point of view (meaning that the pipelined instruction isn't just thrown away). 

However, when emulating programs in _Spim_, I've noticed that it doesn't seem to execute the instruction in the delay slot. Is this a result of the assembler simply filling the delay slot with a `nop`? Should we be implementing delay slot execution or just jumping directly?

This possibly also highlights places where simulators differ from the specification...

**Comment by ps-george** [comment]
![screenshot from 2016-10-19 18-34-35](https://cloud.githubusercontent.com/assets/17267419/19530848/7251a0ea-962d-11e6-9865-d7c2ef77c077.png)
This excerpt from run_addu.cpp implies that we should be implementing delay slot execution :)
