### ISSUE TITLE
Disassembling instructions

### ISSUE THREAD

**Issue by ZoeSlattery** [m8pple/arch2-2015-cw1#32]
Hi, we were wondering if it is necessary to create a function to disassemble an instruction such as "addu r1, r2, r3", turning this into binary code. If so, where should it go in the program? We're unclear as to whether writing such a function is just to make our lives easier later or if it is a requirement within the cpu?

**Comment by m8pple** [comment]
I think you mean an assembler ?:
- Disassemble: take a binary instruction and turn into assembly
- Assemble: take the assembly and turn it into binary instruction

An assembler is useful on the test side. A dis-assembler could be
useful on the CPU side for debugging purposes (e.g. the CPU prints
the instructions as it executes them).

It is mainly a question of making life easier. You'll need to create quite a few instructions
for testing purposes, so it is the difference between:

Working out every instruction in hex:

```
uint32_t instr=0x1232312;
```

Constructing every instruction from scratch:

```
uint32_t instr=(0<<28) | (2<<17) | (5<<10) | (3<<5) ; // Made up fields, not MIPS!
```

Or having a helper function:

```
uint32_t instr=make_r_type( 4, 5, 6, 0, 7); // Make r-type with dst=4, srcs=[5,6], shift=0, alu=7
```

Or having a cleverer helper function:

```
uint32_t instr = make_instr("addu $4, $5, $6");
```

Ultimately they all just create instructions, but there is the trade-off between how
long it takes. For many people the `make_r_type` function is probably about the
right level, as it is a simple function to write that saves a lot of time.

A full assembler is kind of cool, but takes a bit more effort for less clear benefits,
