### ISSUE TITLE
Ambiguity in the instruction complexities

### ISSUE THREAD

**Issue by JB515** [m8pple/arch2-2015-cw1#4]
In the list of instructions to implement, the move instructions are listed with complexity "3 XXXX". This is also the case for DIVU and MULTU. Also, SLLV is listed as "3 XX". Are these instructions 3 or 4 (or 2)?

**Comment by m8pple** [comment]
I was trying to update the difficulties according to what students found most difficult to
get right last time, so it is a bit of a guess.

But yes, they are inconsistent. I'll synchronise the Xs with the numbers.
