### ISSUE TITLE
Test dependencies

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#40]
Is it okay if a few of my tests depend on other things working?

For the MULT/DIV example it's obvious that there is some kind of dependency on MFHI/MFLO for testing.

However in testing my branching/jumping instructions, I rely on a simple ADDU in the delay slot and at the target location to test whether the delay slot and jumping both work correctly... However, if ADDU doesn't work, my testing program may (wrongly) say none of the JUMP/BRANCH functions work.

But, I have to use some kind of instruction other than J to test whether the CPU correctly executes the delay slot instruction and also correctly executes the instruction jumped to. ADDU seems the most obvious choice...

**Comment by m8pple** [comment]
Yes, some dependencies are fine.

This is a necessary consequence of the limited API I chose - sometimes
you have to use multiple instructions to test one.

I would agree that ADDU is the obvious choice, it is historically by far
the most likely to be working.
