### ISSUE TITLE
Subtle bug in mem code

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#41]
Will the [subtle bug](https://github.com/m8pple/arch2-2016-cw/blob/master/src/shared/mips_mem_ram.cpp#L60) still be present in the code used for testing? 

When passing a negative address (or an extremely large positive address, but that is extremely unlikely) to mem_read, `address+length` may overflow, causing the condition `(address+length) > mem->length` to return false (and ultimately a segmentation fault (core dumped) on my program). This can be fixed by adding another condition: `address > (UINT32_MAX - length)`. It can also be prevented on the CPU side by building in a safeguard that prevents passing negative values to the memory handler.

I can build a safeguard into my CPU, but others' CPUs may not have the same protection and **will** crash my test program when I test for mips_ExceptionInvalidAddress from a branch to a negative address. Shall I not test that condition or shall I assume the test code will not have the subtle bug?

**Comment by ps-george** [comment]
Also, is it correct to build a check into my CPU to return an error in this case? 

One could expect the CPU to execute the branch instruction, execute the delay slot instruction, THEN return an error because the memory address is invalid.

But with the safeguard, it will simply return an error instantly.

**Comment by m8pple** [comment]
Your fix sounds splendid - would you like to submit a pull request?

If you go into that file in the github website and edit it, then github
will give you the option of submitting it as a pull request (I believe it will
ask you to fork the repo, then submit a pull from your branch).

If you're worried about typing it in wrong, then you can prepare the
edit beforehand, then paste it in. Even better:
- fork this repository
- clone a local copy
- prepare the change in your local copy and test it
- commit in your local repository
- push changes from your local copy up to your fork
- send a pull request from fork to this repository

**Comment by m8pple** [comment]
Thanks muchly.

I'd like to pretend I did some kind of continuous integration test before accepting
the pull, but it's more a case of "do what we say, not what we do".
