### ISSUE TITLE
Testing mips_error return values

### ISSUE THREAD

**Issue by fpgamy** [m8pple/arch2-2015-cw1#47]
This question relates to issue #16 however I am still unsure of the return value from instructions which result in undefined behaviour. The specification states that operations such as divide by 0 result in an undefined arithmetic result and the DIV operation does not return any arithmetic exception. Similarly there are scenarios where a MFHI or MFLO operation could access registers with undefined values. 

The specification also states when an Address Error should be thrown, however mips_core defines both mips_ExceptionInvalidAlignment and mips_ExceptionInvalidAddress. 

My questions are:
1. Are these scenarios examples where ExceptionBreak and AccessViolation should be thrown or should both return mips_Success? (if not, could you provide an example of where these errors could be used?)
2. If an incorrect error/exception is thrown should we report test failed? (more specifically: if an address is invalid for more than one reason, should it matter which of the 2 address errors are thrown?)

**Comment by m8pple** [comment]
From the MIPS point of view, undefined is just undefined - so if a divide by 0 happens, then the
instruction will complete successfully (mips_Success). What is then left in the hi/lo registers
is up to the CPU. It can choose something convenient, fill them with random values, set them
to zero - whatever it prefers. So the MIPS view of undefined only applies to the values left in
the registers, not to what happens to the control-path afterwards.

(This is different to the C++ view of undefined _behaviour_, which can apply to both the
data and control of a program - so if you don't return a value from a function, then the
compiler could return a random value, but it could also crash the program or fail to return
to the right place).

In terms of memory address errors, consider the following memory map:
- 0x0000 - 0x0FFF : Instructions mapped into ROM
- 0x1000 - 0x1FFF : Data mapped into RAM
- 0x2000 - 0xFFFFFFFF : no mapping

Then what errors should I get if I do:

```
sw $0, 0($0)   # Write to address 0 (trying to _access_ a ROM as if it is a RAM)

lw $0, 1($0)   # Read from address 1

lw $0, 0x4000($0) # Read from address 0x4000
```

There are some cases which hit more than one error, e.g.:

```
sw $0, 0($0)  # Write to address 0
```

However, the above is surely not an invalid address (as there exists
something at that address). So yes, there could be some
precedence on the errors. I haven't specified such a precedence,
as to a certain extent it doesn't matter too much.

For ExceptionBreak - we are not implementing all the MIPS instructions. There
is also a BREAK instruction. (I suppose I could have put ExceptionSysCall in
there as well).

I would not be inclined to check precisely for an error, unless you know
precisely what error should occur. So if you set up an arithmetic
overflow, you know it must be exactly arithmetic exception. If you
put in a misaligned pointer in a valid memory region, it must be
an alignment error.

So when you are testing, make sure only one thing can go wrong :)
