### ISSUE TITLE
Endian

### ISSUE THREAD

**Issue by ZoeSlattery** [m8pple/arch2-2015-cw1#48]
Hi, I'm still confused by load and store and whether the endianness of a byte/halfword/word would need to be changed when putting it in or taking it out of memory. Was wondering if could talk it through in computing labs at 1 today?

**Comment by m8pple** [comment]
Sorry, today and yesterday I was block booked through with teaching/meetings.

The general approach is that the thing in RAM should be treated as an
integer for loading purposes.

So if you load a word from address `a`, then the integer should be:

```
 mem(a) * 2^24 + mem(a+1) * 2^16 + mem(a+2) * 2^8 + mem(a+3) * 2^0
```

while if you load a half-word, then the integer is:

```
 mem(a) * 2^8 + mem(a+1) * 2^0
```

and for a byte the integer is:

```
 mem(a) * 2^0
```

When you store a word/half-word/byte then you are reversing the process.
