### ISSUE TITLE
Printing to stderr while running test_mips.cpp

### ISSUE THREAD

**Issue by ps-george** [m8pple/arch2-2015-cw1#49]
Is it okay to print messages to stderr?

I print ongoing stats so it's easy for the user to pinpoint the error that caused the problem i.e.
Testing `testid` Description: `msg` Result: `pass/fail`

And also warnings before testing dangerous things that may crash the CPU, like divide by 0 or invalid handle test.

**Comment by m8pple** [comment]
Yes, that is fine. Printing to stderr is generally fair game, as it is expected
to not be part of the application output.
