### ISSUE TITLE
Potential ambiguity with regard to manually setting PC just after a jump.

### ISSUE THREAD

**Issue by tomhartley** [m8pple/arch2-2015-cw1#6]
As discussed - if, for example, right after a J(ump) instruction at X to Z, if PC is set to Y, I can invisage a couple of outcomes. The spec clearly states that using mips_cpu_set_pc sets the address of the next instruction. So:
Next instruction after J is Y, and them Y+4, etc.
or - 
Next instruction after J is Y, and then Z, Z+4, etc.

The first option might be more useful from a debugging/testing perspective, given that's what mips_cpu_set_pc is designed for.

**Comment by m8pple** [comment]
I agree that the first interpretation is the one that is more useful, but further I would
argue that it also that it is the only one that makes the CPU useable.

If we take option two, then the question becomes "how can the user force the
execution of any sequence of instructions?". So if you imagine putting two
instructions at 0x1000 and 0x1004, how can you use `mips_cpu_set_pc` to
make the CPU execute both on successive calls to `mips_cpu_step`? Under
option two, we can force the first instruction to execute, but then a potentially
unknown instruction will execute next. Ok, so we'd need to call `mips_cpu_set_pc`
again, and now we can execute two instructions.

Going further, imagine n instructions in a sequence. If we take option 2,
then we would need to call `mips_cpu_set_pc` before _every_ instruction,
as we have no way of explicitly setting pcNext. The only way we get to
escape that is if the processor encounters a jump instruction, and _then_
it will set pcNext and we can stop forcing the processor back onto the
correct track.

So we would have to set the test instructions up such that the first instruction
was a jump, which then branches to the _actual_ test-code. That means it
would be impossible to test sequences of data-path instructions at any
other address than zero without also testing control-path.

But... if we have the convention that `mips_cpu_set_pc` does not change
pcNext, then what happens on a reset? A literal intepretation of the spec
for `mips_cpu_reset`, is that it sets _all_ registers to zero, so it would have
pc==pcNext==0. That would mean that you would have to call `mips_cpu_set_pc`
before _any_ instruction stream, even those starting at address zero. Which
by extension means that there must always be a test instruction at address
zero.

However... address zero might not exist, or it might contain something
other than memory.

Exploring the options like this shows that is isn't really feasible to choose
option 2 and still be able to perform arbitrary tests.

Which is all a long-winded way of saying - yeah, option 1 is the way to go.
